name: CI/CD symfony-shop

on: 
  push:
    branches: 
      - main
    tags:
      - '*'  # Triggers for tags

permissions: 
  contents: read
  packages: write

jobs: 
  ci-cd:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/catherine-tranchand/symfony-shop
      REGISTRY: ghcr.io

    steps: 
      
       # 1. Récupération du code source

      - name: Checkout symfony-shop Repo
        uses: actions/checkout@v3
        with: 
          repository: catherine-tranchand/symfony-shop
          token: ${{ secrets.SYMFONY_REPO_TOKEN }}

      - name: List Workspace Files
        run: ls -la


      # 2. Lancer les tests
      - name: Run tests
        run: |
          echo "Running tests..."
          composer require symfonycasts/tailwind-bundle
          composer install
  
      # 3. Envoyer les notifications via GoogleChat

      - name: Send Notifications to Google Chat
        run: |
          curl -X POST ${{ secrets.GOOGLE_CHAT_WEBHOOK }} \
          -H 'Content-Type: application/json' \
          -d '{
                "text": "Pipeline Status: Success\n
                Commit: ${{ github.sha }}\n
                Branch/Tag: ${{ github.ref_name}}"
          }'
        if: success() || failure()      



  
 
