name: CI/CD symfony-shop

on: 
  push:
    branches: 
      - main
    tags:
      - '*'  # Triggers for tags

permissions: 
  contents: read
  packages: write

jobs: 
  ci-cd:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/catherine-tranchand/symfony-shop
      REGISTRY: ghcr.io

    steps: 
      # 1. Checkout the repository
      - name: Checkout symfony-shop Repo
        uses: actions/checkout@v3
        with: 
          repository: catherine-tranchand/symfony-shop
          token: ${{ secrets.SYMFONY_REPO_TOKEN }}

      # 2. List workspace files
      - name: List Workspace Files
        run: ls -la

      # 3. Run tests
      - name: Run tests
        run: |
          echo "Running tests..."
          composer require symfonycasts/tailwind-bundle
          composer install
  
      # 4. Send notifications via Google Chat
      - name: Send Notifications to Google Chat
        run: |
          curl -X POST "${{ secrets.GOOGLE_CHAT_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
            "text": "Pipeline Status: Success\nCommit: '${{ github.sha }}'\nBranch/Tag: '${{ github.ref_name }}'"
          }'
        if: always()

        





  
 
