name: CI/CD module de connexion

on: 
  push:
    branches: 
      - main
    tags:
      - '*'  # Triggers for tags

permissions: 
  contents: read
  packages: write

jobs: 
  ci-cd:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ghcr.io/catherine-tranchand/symfony-shop
      REGISTRY: ghcr.io

    steps: 
      
       # 1. Récupération du code source

      - name: Checkout symfony-shop Repo
        uses: actions/checkout@v3
        with: 
          repository: catherine-tranchand/symfony-shop
          token: ${{ secrets.SYMFONYSHOP_REPO_TOKEN }}

      # 2. Lancer les tests
      - name: Run tests
        run: |
          echo "Running tests..."
          cd symfony-shop
          composer require symfonycasts/tailwind-bundle



  
 
